# global config
server:
  port: 11302

model-server-endpoint: http://alpacapaca.dreamgonfly.me:5000

logging:
  level:
    root: info

management:
  security:
    enabled: false
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://db_url:3306/db_name?useUnicode=true&characterEncoding=utf8
    username: secret
    password: secret

